// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.projectplayer.onyx_player_android

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Où en est le lecteur, dans le vocabulaire d'ExoPlayer. */
enum class OnyxPlaybackState(val raw: Int) {
  /** Rien de chargé. */
  IDLE(0),
  /** Chargé, mais pas assez de données pour avancer. */
  BUFFERING(1),
  /** Prêt à jouer, ou en train de jouer. */
  READY(2),
  /** Arrivé au bout. */
  ENDED(3);

  companion object {
    fun ofRaw(raw: Int): OnyxPlaybackState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Pourquoi une ouverture a échoué.
 *
 * Le détail importe : c'est ce qui distingue un fichier qu'il faut transcoder
 * d'un réseau qui a lâché, et donc s'il faut réessayer ou changer de source.
 */
enum class OnyxPlayerErrorKind(val raw: Int) {
  /**
   * Le conteneur ou le codec n'est pas lisible par cet appareil. C'est le cas
   * qui bascule sur le transcodage.
   */
  UNSUPPORTED(0),
  /** La source n'a pas pu être lue : réseau, 404, connexion coupée. */
  SOURCE(1),
  /** Tout le reste. */
  UNKNOWN(2);

  companion object {
    fun ofRaw(raw: Int): OnyxPlayerErrorKind? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class OnyxVideoSize (
  val width: Long,
  val height: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OnyxVideoSize {
      val width = pigeonVar_list[0] as Long
      val height = pigeonVar_list[1] as Long
      return OnyxVideoSize(width, height)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      width,
      height,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as OnyxVideoSize
    return MessagesPigeonUtils.deepEquals(this.width, other.width) && MessagesPigeonUtils.deepEquals(this.height, other.height)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.width)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.height)
    return result
  }
  override fun toString(): String {
    return "OnyxVideoSize(width=$width, height=$height)"
  }
}

/**
 * Un instantané complet de l'état du lecteur.
 *
 * Un seul objet plutôt qu'un événement par propriété : l'appelant n'a qu'un
 * état à réconcilier, et deux champs ne peuvent pas se contredire en chemin.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class OnyxPlayerStatus (
  val playerId: Long,
  val state: OnyxPlaybackState,
  /** Le lecteur avance réellement — distinct de « on lui a demandé de lire ». */
  val isPlaying: Boolean,
  val positionMs: Long,
  /** 0 tant qu'ExoPlayer ne connaît pas la durée (flux en cours de sondage). */
  val durationMs: Long,
  val bufferedPositionMs: Long,
  /** Null tant que le décodeur n'a pas annoncé les dimensions. */
  val videoSize: OnyxVideoSize? = null,
  val errorKind: OnyxPlayerErrorKind? = null,
  val errorMessage: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OnyxPlayerStatus {
      val playerId = pigeonVar_list[0] as Long
      val state = pigeonVar_list[1] as OnyxPlaybackState
      val isPlaying = pigeonVar_list[2] as Boolean
      val positionMs = pigeonVar_list[3] as Long
      val durationMs = pigeonVar_list[4] as Long
      val bufferedPositionMs = pigeonVar_list[5] as Long
      val videoSize = pigeonVar_list[6] as OnyxVideoSize?
      val errorKind = pigeonVar_list[7] as OnyxPlayerErrorKind?
      val errorMessage = pigeonVar_list[8] as String?
      return OnyxPlayerStatus(playerId, state, isPlaying, positionMs, durationMs, bufferedPositionMs, videoSize, errorKind, errorMessage)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      playerId,
      state,
      isPlaying,
      positionMs,
      durationMs,
      bufferedPositionMs,
      videoSize,
      errorKind,
      errorMessage,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as OnyxPlayerStatus
    return MessagesPigeonUtils.deepEquals(this.playerId, other.playerId) && MessagesPigeonUtils.deepEquals(this.state, other.state) && MessagesPigeonUtils.deepEquals(this.isPlaying, other.isPlaying) && MessagesPigeonUtils.deepEquals(this.positionMs, other.positionMs) && MessagesPigeonUtils.deepEquals(this.durationMs, other.durationMs) && MessagesPigeonUtils.deepEquals(this.bufferedPositionMs, other.bufferedPositionMs) && MessagesPigeonUtils.deepEquals(this.videoSize, other.videoSize) && MessagesPigeonUtils.deepEquals(this.errorKind, other.errorKind) && MessagesPigeonUtils.deepEquals(this.errorMessage, other.errorMessage)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.playerId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.state)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.isPlaying)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.positionMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.durationMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.bufferedPositionMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.videoSize)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.errorKind)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.errorMessage)
    return result
  }
  override fun toString(): String {
    return "OnyxPlayerStatus(playerId=$playerId, state=$state, isPlaying=$isPlaying, positionMs=$positionMs, durationMs=$durationMs, bufferedPositionMs=$bufferedPositionMs, videoSize=$videoSize, errorKind=$errorKind, errorMessage=$errorMessage)"
  }
}

/**
 * Ce qu'il faut pour répondre à « est-ce que c'est fluide ? » par un chiffre.
 *
 * C'est le critère de recette du premier jalon : comparable au
 * `frame-drop-count` que le lecteur mpv journalise déjà en sortie.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class OnyxPlaybackStats (
  val droppedFrames: Long,
  val renderedFrames: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OnyxPlaybackStats {
      val droppedFrames = pigeonVar_list[0] as Long
      val renderedFrames = pigeonVar_list[1] as Long
      return OnyxPlaybackStats(droppedFrames, renderedFrames)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      droppedFrames,
      renderedFrames,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as OnyxPlaybackStats
    return MessagesPigeonUtils.deepEquals(this.droppedFrames, other.droppedFrames) && MessagesPigeonUtils.deepEquals(this.renderedFrames, other.renderedFrames)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.droppedFrames)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.renderedFrames)
    return result
  }
  override fun toString(): String {
    return "OnyxPlaybackStats(droppedFrames=$droppedFrames, renderedFrames=$renderedFrames)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          OnyxPlaybackState.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          OnyxPlayerErrorKind.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OnyxVideoSize.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OnyxPlayerStatus.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OnyxPlaybackStats.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is OnyxPlaybackState -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is OnyxPlayerErrorKind -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is OnyxVideoSize -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is OnyxPlayerStatus -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is OnyxPlaybackStats -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

val MessagesPigeonMethodCodec = StandardMethodCodec(MessagesPigeonCodec())

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface OnyxPlayerApi {
  /**
   * Crée un lecteur et rend son identifiant. La vue de rendu s'y rattache par
   * cet identifiant, ce qui permet de créer le lecteur avant que la vue
   * n'existe — et de survivre à sa reconstruction.
   */
  fun create(): Long
  /**
   * Détruit le lecteur. Sans appel, ExoPlayer garde son décodeur et sa
   * connexion réseau ouverts.
   */
  fun release(playerId: Long)
  /**
   * Charge [url] et se positionne à [startPositionMs] dans le même geste.
   * Ouvrir puis chercher ferait payer deux fois la mise en mémoire tampon.
   */
  fun open(playerId: Long, url: String, startPositionMs: Long)
  fun play(playerId: Long)
  fun pause(playerId: Long)
  fun seekTo(playerId: Long, positionMs: Long)
  /**
   * L'état à cet instant. Les changements arrivent par le flux d'événements ;
   * ceci sert à s'amorcer sans attendre le premier.
   */
  fun status(playerId: Long): OnyxPlayerStatus
  /** Les compteurs d'images du rendu vidéo. */
  fun stats(playerId: Long): OnyxPlaybackStats

  companion object {
    /** The codec used by OnyxPlayerApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `OnyxPlayerApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: OnyxPlayerApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.onyx_player_android.OnyxPlayerApi.create$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.create())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.onyx_player_android.OnyxPlayerApi.release$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.release(playerIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.onyx_player_android.OnyxPlayerApi.open$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val urlArg = args[1] as String
            val startPositionMsArg = args[2] as Long
            val wrapped: List<Any?> = try {
              api.open(playerIdArg, urlArg, startPositionMsArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.onyx_player_android.OnyxPlayerApi.play$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.play(playerIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.onyx_player_android.OnyxPlayerApi.pause$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.pause(playerIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.onyx_player_android.OnyxPlayerApi.seekTo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val positionMsArg = args[1] as Long
            val wrapped: List<Any?> = try {
              api.seekTo(playerIdArg, positionMsArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.onyx_player_android.OnyxPlayerApi.status$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              listOf(api.status(playerIdArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.onyx_player_android.OnyxPlayerApi.stats$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              listOf(api.stats(playerIdArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}

private class MessagesPigeonStreamHandler<T>(
    val wrapper: MessagesPigeonEventChannelWrapper<T>
) : EventChannel.StreamHandler {
  var pigeonSink: PigeonEventSink<T>? = null

  override fun onListen(p0: Any?, sink: EventChannel.EventSink) {
    pigeonSink = PigeonEventSink<T>(sink)
    wrapper.onListen(p0, pigeonSink!!)
  }

  override fun onCancel(p0: Any?) {
    pigeonSink = null
    wrapper.onCancel(p0)
  }
}

interface MessagesPigeonEventChannelWrapper<T> {
  open fun onListen(p0: Any?, sink: PigeonEventSink<T>) {}

  open fun onCancel(p0: Any?) {}
}

class PigeonEventSink<T>(private val sink: EventChannel.EventSink) {
  fun success(value: T) {
    sink.success(value)
  }

  fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
    sink.error(errorCode, errorMessage, errorDetails)
  }

  fun endOfStream() {
    sink.endOfStream()
  }
}
      
abstract class StatusChangedStreamHandler : MessagesPigeonEventChannelWrapper<OnyxPlayerStatus> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: StatusChangedStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.onyx_player_android.OnyxPlayerEventApi.statusChanged"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = MessagesPigeonStreamHandler<OnyxPlayerStatus>(streamHandler)
      EventChannel(messenger, channelName, MessagesPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from MessagesPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<OnyxPlayerStatus>) {}

override fun onCancel(p0: Any?) {}
}
      
