// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.projectplayer.onyx_player_android

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Où en est le lecteur, dans le vocabulaire d'ExoPlayer. */
enum class OnyxPlaybackState(val raw: Int) {
  /** Rien de chargé. */
  IDLE(0),
  /** Chargé, mais pas assez de données pour avancer. */
  BUFFERING(1),
  /** Prêt à jouer, ou en train de jouer. */
  READY(2),
  /** Arrivé au bout. */
  ENDED(3);

  companion object {
    fun ofRaw(raw: Int): OnyxPlaybackState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Pourquoi une ouverture a échoué.
 *
 * Le détail importe : c'est ce qui distingue un fichier qu'il faut transcoder
 * d'un réseau qui a lâché, et donc s'il faut réessayer ou changer de source.
 */
enum class OnyxPlayerErrorKind(val raw: Int) {
  /**
   * Le conteneur ou le codec n'est pas lisible par cet appareil. C'est le cas
   * qui bascule sur le transcodage.
   */
  UNSUPPORTED(0),
  /** La source n'a pas pu être lue : réseau, 404, connexion coupée. */
  SOURCE(1),
  /** Tout le reste. */
  UNKNOWN(2);

  companion object {
    fun ofRaw(raw: Int): OnyxPlayerErrorKind? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Comment l'image remplit sa surface.
 *
 * Une `SurfaceView` est une couche du système : Flutter ne peut pas la mettre
 * à l'échelle, donc le cadrage se décide côté natif. C'est ce qui fait
 * répondre le pincement et le réglage « taille adaptative » sur Android.
 */
enum class OnyxVideoFit(val raw: Int) {
  /** L'image entière, avec des bandes s'il le faut. */
  CONTAIN(0),
  /** La surface entière, en rognant ce qui dépasse. */
  COVER(1);

  companion object {
    fun ofRaw(raw: Int): OnyxVideoFit? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Une piste que le moteur a énumérée.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class OnyxTrack (
  val id: String,
  val title: String? = null,
  val language: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OnyxTrack {
      val id = pigeonVar_list[0] as String
      val title = pigeonVar_list[1] as String?
      val language = pigeonVar_list[2] as String?
      return OnyxTrack(id, title, language)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      title,
      language,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as OnyxTrack
    return MessagesPigeonUtils.deepEquals(this.id, other.id) && MessagesPigeonUtils.deepEquals(this.title, other.title) && MessagesPigeonUtils.deepEquals(this.language, other.language)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.id)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.title)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.language)
    return result
  }
  override fun toString(): String {
    return "OnyxTrack(id=$id, title=$title, language=$language)"
  }
}

/**
 * Les tampons, dans les unités d'ExoPlayer.
 *
 * `PlaybackProfile` les exprime en octets et en secondes, parce que c'est le
 * vocabulaire de mpv ; `DefaultLoadControl` ne connaît que des millisecondes.
 * La traduction se fait côté Dart, où le profil est déjà résolu.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class OnyxLoadTuning (
  val minBufferMs: Long,
  val maxBufferMs: Long,
  /**
   * Ce qu'il faut avoir en mémoire avant que l'image ne parte. Court : c'est
   * du temps ajouté devant la première image, à chaque ouverture.
   */
  val bufferForPlaybackMs: Long,
  /**
   * Ce qu'on garde derrière la tête de lecture, pour que le retour de 10 s ne
   * reparte pas sur le réseau.
   */
  val backBufferMs: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OnyxLoadTuning {
      val minBufferMs = pigeonVar_list[0] as Long
      val maxBufferMs = pigeonVar_list[1] as Long
      val bufferForPlaybackMs = pigeonVar_list[2] as Long
      val backBufferMs = pigeonVar_list[3] as Long
      return OnyxLoadTuning(minBufferMs, maxBufferMs, bufferForPlaybackMs, backBufferMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      minBufferMs,
      maxBufferMs,
      bufferForPlaybackMs,
      backBufferMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as OnyxLoadTuning
    return MessagesPigeonUtils.deepEquals(this.minBufferMs, other.minBufferMs) && MessagesPigeonUtils.deepEquals(this.maxBufferMs, other.maxBufferMs) && MessagesPigeonUtils.deepEquals(this.bufferForPlaybackMs, other.bufferForPlaybackMs) && MessagesPigeonUtils.deepEquals(this.backBufferMs, other.backBufferMs)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.minBufferMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.maxBufferMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.bufferForPlaybackMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.backBufferMs)
    return result
  }
  override fun toString(): String {
    return "OnyxLoadTuning(minBufferMs=$minBufferMs, maxBufferMs=$maxBufferMs, bufferForPlaybackMs=$bufferForPlaybackMs, backBufferMs=$backBufferMs)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class OnyxVideoSize (
  val width: Long,
  val height: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OnyxVideoSize {
      val width = pigeonVar_list[0] as Long
      val height = pigeonVar_list[1] as Long
      return OnyxVideoSize(width, height)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      width,
      height,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as OnyxVideoSize
    return MessagesPigeonUtils.deepEquals(this.width, other.width) && MessagesPigeonUtils.deepEquals(this.height, other.height)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.width)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.height)
    return result
  }
  override fun toString(): String {
    return "OnyxVideoSize(width=$width, height=$height)"
  }
}

/**
 * Un instantané complet de l'état du lecteur.
 *
 * Un seul objet plutôt qu'un événement par propriété : l'appelant n'a qu'un
 * état à réconcilier, et deux champs ne peuvent pas se contredire en chemin.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class OnyxPlayerStatus (
  val playerId: Long,
  val state: OnyxPlaybackState,
  /** Le lecteur avance réellement — distinct de « on lui a demandé de lire ». */
  val isPlaying: Boolean,
  val positionMs: Long,
  /** 0 tant qu'ExoPlayer ne connaît pas la durée (flux en cours de sondage). */
  val durationMs: Long,
  val bufferedPositionMs: Long,
  /** Null tant que le décodeur n'a pas annoncé les dimensions. */
  val videoSize: OnyxVideoSize? = null,
  /** Les pistes que le moteur a trouvées dans ce média. */
  val audioTracks: List<OnyxTrack>,
  val subtitleTracks: List<OnyxTrack>,
  val selectedAudioTrackId: String? = null,
  val selectedSubtitleTrackId: String? = null,
  /**
   * Les lignes de sous-titre à afficher maintenant. Rendues côté Flutter, pour
   * que l'habillage soit le même que sur les autres plateformes.
   */
  val subtitleCues: List<String>,
  val errorKind: OnyxPlayerErrorKind? = null,
  val errorMessage: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OnyxPlayerStatus {
      val playerId = pigeonVar_list[0] as Long
      val state = pigeonVar_list[1] as OnyxPlaybackState
      val isPlaying = pigeonVar_list[2] as Boolean
      val positionMs = pigeonVar_list[3] as Long
      val durationMs = pigeonVar_list[4] as Long
      val bufferedPositionMs = pigeonVar_list[5] as Long
      val videoSize = pigeonVar_list[6] as OnyxVideoSize?
      val audioTracks = pigeonVar_list[7] as List<OnyxTrack>
      val subtitleTracks = pigeonVar_list[8] as List<OnyxTrack>
      val selectedAudioTrackId = pigeonVar_list[9] as String?
      val selectedSubtitleTrackId = pigeonVar_list[10] as String?
      val subtitleCues = pigeonVar_list[11] as List<String>
      val errorKind = pigeonVar_list[12] as OnyxPlayerErrorKind?
      val errorMessage = pigeonVar_list[13] as String?
      return OnyxPlayerStatus(playerId, state, isPlaying, positionMs, durationMs, bufferedPositionMs, videoSize, audioTracks, subtitleTracks, selectedAudioTrackId, selectedSubtitleTrackId, subtitleCues, errorKind, errorMessage)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      playerId,
      state,
      isPlaying,
      positionMs,
      durationMs,
      bufferedPositionMs,
      videoSize,
      audioTracks,
      subtitleTracks,
      selectedAudioTrackId,
      selectedSubtitleTrackId,
      subtitleCues,
      errorKind,
      errorMessage,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as OnyxPlayerStatus
    return MessagesPigeonUtils.deepEquals(this.playerId, other.playerId) && MessagesPigeonUtils.deepEquals(this.state, other.state) && MessagesPigeonUtils.deepEquals(this.isPlaying, other.isPlaying) && MessagesPigeonUtils.deepEquals(this.positionMs, other.positionMs) && MessagesPigeonUtils.deepEquals(this.durationMs, other.durationMs) && MessagesPigeonUtils.deepEquals(this.bufferedPositionMs, other.bufferedPositionMs) && MessagesPigeonUtils.deepEquals(this.videoSize, other.videoSize) && MessagesPigeonUtils.deepEquals(this.audioTracks, other.audioTracks) && MessagesPigeonUtils.deepEquals(this.subtitleTracks, other.subtitleTracks) && MessagesPigeonUtils.deepEquals(this.selectedAudioTrackId, other.selectedAudioTrackId) && MessagesPigeonUtils.deepEquals(this.selectedSubtitleTrackId, other.selectedSubtitleTrackId) && MessagesPigeonUtils.deepEquals(this.subtitleCues, other.subtitleCues) && MessagesPigeonUtils.deepEquals(this.errorKind, other.errorKind) && MessagesPigeonUtils.deepEquals(this.errorMessage, other.errorMessage)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.playerId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.state)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.isPlaying)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.positionMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.durationMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.bufferedPositionMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.videoSize)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.audioTracks)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.subtitleTracks)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.selectedAudioTrackId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.selectedSubtitleTrackId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.subtitleCues)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.errorKind)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.errorMessage)
    return result
  }
  override fun toString(): String {
    return "OnyxPlayerStatus(playerId=$playerId, state=$state, isPlaying=$isPlaying, positionMs=$positionMs, durationMs=$durationMs, bufferedPositionMs=$bufferedPositionMs, videoSize=$videoSize, audioTracks=$audioTracks, subtitleTracks=$subtitleTracks, selectedAudioTrackId=$selectedAudioTrackId, selectedSubtitleTrackId=$selectedSubtitleTrackId, subtitleCues=$subtitleCues, errorKind=$errorKind, errorMessage=$errorMessage)"
  }
}

/**
 * Ce qu'il faut pour répondre à « est-ce que c'est fluide ? » par un chiffre.
 *
 * C'est le critère de recette du premier jalon : comparable au
 * `frame-drop-count` que le lecteur mpv journalise déjà en sortie.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class OnyxPlaybackStats (
  val droppedFrames: Long,
  val renderedFrames: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OnyxPlaybackStats {
      val droppedFrames = pigeonVar_list[0] as Long
      val renderedFrames = pigeonVar_list[1] as Long
      return OnyxPlaybackStats(droppedFrames, renderedFrames)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      droppedFrames,
      renderedFrames,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as OnyxPlaybackStats
    return MessagesPigeonUtils.deepEquals(this.droppedFrames, other.droppedFrames) && MessagesPigeonUtils.deepEquals(this.renderedFrames, other.renderedFrames)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.droppedFrames)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.renderedFrames)
    return result
  }
  override fun toString(): String {
    return "OnyxPlaybackStats(droppedFrames=$droppedFrames, renderedFrames=$renderedFrames)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          OnyxPlaybackState.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          OnyxPlayerErrorKind.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          OnyxVideoFit.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OnyxTrack.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OnyxLoadTuning.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OnyxVideoSize.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OnyxPlayerStatus.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OnyxPlaybackStats.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is OnyxPlaybackState -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is OnyxPlayerErrorKind -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is OnyxVideoFit -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is OnyxTrack -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is OnyxLoadTuning -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is OnyxVideoSize -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is OnyxPlayerStatus -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is OnyxPlaybackStats -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

val MessagesPigeonMethodCodec = StandardMethodCodec(MessagesPigeonCodec())

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface OnyxPlayerApi {
  /**
   * Crée un lecteur et rend son identifiant. La vue de rendu s'y rattache par
   * cet identifiant, ce qui permet de créer le lecteur avant que la vue
   * n'existe — et de survivre à sa reconstruction.
   */
  fun create(): Long
  /**
   * Détruit le lecteur. Sans appel, ExoPlayer garde son décodeur et sa
   * connexion réseau ouverts.
   */
  fun release(playerId: Long)
  /**
   * Charge [url] et se positionne à [startPositionMs] dans le même geste.
   * Ouvrir puis chercher ferait payer deux fois la mise en mémoire tampon.
   *
   * [play] démarre la lecture dès que le média est prêt, sans second aller-
   * retour : c'est ce que fait le passage à l'épisode suivant.
   */
  fun open(playerId: Long, url: String, startPositionMs: Long, play: Boolean)
  fun play(playerId: Long)
  fun pause(playerId: Long)
  fun seekTo(playerId: Long, positionMs: Long)
  /**
   * Décharge le média sans détruire le lecteur.
   *
   * C'est ici que le décodeur matériel est rendu — l'opération la plus chère
   * du démontage. L'appeler tôt fait qu'elle se paie pendant qu'autre chose
   * se passe à l'écran, plutôt qu'après.
   */
  fun stop(playerId: Long)
  fun setVolume(playerId: Long, volume: Double)
  fun setRate(playerId: Long, rate: Double)
  /**
   * Quelle langue audio charger d'emblée, la plus probable en premier. Posé
   * avant l'ouverture — après, changer de piste recharge le tampon.
   */
  fun setPreferredAudioLanguages(playerId: Long, priorities: List<String>)
  fun selectAudioTrack(playerId: Long, trackId: String)
  /**
   * Sélectionne une piste de sous-titres interne, ou aucune si [trackId] est
   * nul.
   */
  fun selectSubtitleTrack(playerId: Long, trackId: String?)
  /**
   * Charge un WebVTT que le serveur a produit, en le posant à côté du média.
   *
   * Le contenu est passé plutôt qu'une URL : c'est le contrôleur qui l'a
   * téléchargé, et le serveur a déjà recalé les temps sur l'offset du flux.
   */
  fun setExternalSubtitle(playerId: Long, vttContent: String?, language: String?, title: String?)
  /**
   * Cherche à l'image près, ou au point-clé le plus proche pendant qu'on fait
   * glisser la tête de lecture.
   */
  fun setExactSeek(playerId: Long, exact: Boolean)
  fun setVideoFit(playerId: Long, fit: OnyxVideoFit)
  /**
   * Impose la durée totale : en transcodage, le moteur ne voit que les
   * segments déjà produits.
   */
  fun overrideDuration(playerId: Long, totalMs: Long)
  fun applyTuning(playerId: Long, tuning: OnyxLoadTuning)
  /**
   * Les types MIME audio que la puce sait décoder.
   *
   * mpv décodait tout en logiciel ; ExoPlayer dépend de MediaCodec. Demandé
   * une fois, pour que le contrôleur puisse trancher lecture directe ou
   * transcodage **avant** d'ouvrir, plutôt que d'échouer devant l'utilisateur.
   */
  fun decodableAudioMimeTypes(): List<String>
  /**
   * L'état à cet instant. Les changements arrivent par le flux d'événements ;
   * ceci sert à s'amorcer sans attendre le premier.
   */
  fun status(playerId: Long): OnyxPlayerStatus
  /** Les compteurs d'images du rendu vidéo. */
  fun stats(playerId: Long): OnyxPlaybackStats

  companion object {
    /** The codec used by OnyxPlayerApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `OnyxPlayerApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: OnyxPlayerApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.onyx_player_android.OnyxPlayerApi.create$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.create())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.onyx_player_android.OnyxPlayerApi.release$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.release(playerIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.onyx_player_android.OnyxPlayerApi.open$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val urlArg = args[1] as String
            val startPositionMsArg = args[2] as Long
            val playArg = args[3] as Boolean
            val wrapped: List<Any?> = try {
              api.open(playerIdArg, urlArg, startPositionMsArg, playArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.onyx_player_android.OnyxPlayerApi.play$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.play(playerIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.onyx_player_android.OnyxPlayerApi.pause$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.pause(playerIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.onyx_player_android.OnyxPlayerApi.seekTo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val positionMsArg = args[1] as Long
            val wrapped: List<Any?> = try {
              api.seekTo(playerIdArg, positionMsArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.onyx_player_android.OnyxPlayerApi.stop$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.stop(playerIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.onyx_player_android.OnyxPlayerApi.setVolume$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val volumeArg = args[1] as Double
            val wrapped: List<Any?> = try {
              api.setVolume(playerIdArg, volumeArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.onyx_player_android.OnyxPlayerApi.setRate$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val rateArg = args[1] as Double
            val wrapped: List<Any?> = try {
              api.setRate(playerIdArg, rateArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.onyx_player_android.OnyxPlayerApi.setPreferredAudioLanguages$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val prioritiesArg = args[1] as List<String>
            val wrapped: List<Any?> = try {
              api.setPreferredAudioLanguages(playerIdArg, prioritiesArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.onyx_player_android.OnyxPlayerApi.selectAudioTrack$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val trackIdArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.selectAudioTrack(playerIdArg, trackIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.onyx_player_android.OnyxPlayerApi.selectSubtitleTrack$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val trackIdArg = args[1] as String?
            val wrapped: List<Any?> = try {
              api.selectSubtitleTrack(playerIdArg, trackIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.onyx_player_android.OnyxPlayerApi.setExternalSubtitle$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val vttContentArg = args[1] as String?
            val languageArg = args[2] as String?
            val titleArg = args[3] as String?
            val wrapped: List<Any?> = try {
              api.setExternalSubtitle(playerIdArg, vttContentArg, languageArg, titleArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.onyx_player_android.OnyxPlayerApi.setExactSeek$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val exactArg = args[1] as Boolean
            val wrapped: List<Any?> = try {
              api.setExactSeek(playerIdArg, exactArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.onyx_player_android.OnyxPlayerApi.setVideoFit$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val fitArg = args[1] as OnyxVideoFit
            val wrapped: List<Any?> = try {
              api.setVideoFit(playerIdArg, fitArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.onyx_player_android.OnyxPlayerApi.overrideDuration$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val totalMsArg = args[1] as Long
            val wrapped: List<Any?> = try {
              api.overrideDuration(playerIdArg, totalMsArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.onyx_player_android.OnyxPlayerApi.applyTuning$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val tuningArg = args[1] as OnyxLoadTuning
            val wrapped: List<Any?> = try {
              api.applyTuning(playerIdArg, tuningArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.onyx_player_android.OnyxPlayerApi.decodableAudioMimeTypes$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.decodableAudioMimeTypes())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.onyx_player_android.OnyxPlayerApi.status$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              listOf(api.status(playerIdArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.onyx_player_android.OnyxPlayerApi.stats$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              listOf(api.stats(playerIdArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}

private class MessagesPigeonStreamHandler<T>(
    val wrapper: MessagesPigeonEventChannelWrapper<T>
) : EventChannel.StreamHandler {
  var pigeonSink: PigeonEventSink<T>? = null

  override fun onListen(p0: Any?, sink: EventChannel.EventSink) {
    pigeonSink = PigeonEventSink<T>(sink)
    wrapper.onListen(p0, pigeonSink!!)
  }

  override fun onCancel(p0: Any?) {
    pigeonSink = null
    wrapper.onCancel(p0)
  }
}

interface MessagesPigeonEventChannelWrapper<T> {
  open fun onListen(p0: Any?, sink: PigeonEventSink<T>) {}

  open fun onCancel(p0: Any?) {}
}

class PigeonEventSink<T>(private val sink: EventChannel.EventSink) {
  fun success(value: T) {
    sink.success(value)
  }

  fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
    sink.error(errorCode, errorMessage, errorDetails)
  }

  fun endOfStream() {
    sink.endOfStream()
  }
}
      
abstract class StatusChangedStreamHandler : MessagesPigeonEventChannelWrapper<OnyxPlayerStatus> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: StatusChangedStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.onyx_player_android.OnyxPlayerEventApi.statusChanged"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = MessagesPigeonStreamHandler<OnyxPlayerStatus>(streamHandler)
      EventChannel(messenger, channelName, MessagesPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from MessagesPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<OnyxPlayerStatus>) {}

override fun onCancel(p0: Any?) {}
}
      
