// Autogenerated from Pigeon (v28.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// Où en est le lecteur. Le même vocabulaire que sur Android, pour que les
/// deux sessions de l'app se lisent de la même façon.
enum OnyxApplePlaybackState {
  /// Rien de chargé, ou lecture arrêtée.
  idle,
  /// Ouverture, saut ou réserve vide : l'image n'avance pas en attendant des
  /// données.
  buffering,
  /// Prêt à jouer, ou en train de jouer.
  ready,
  /// Arrivé au bout. Terminal : il faut rouvrir pour relire.
  ended,
}

/// Pourquoi une ouverture a échoué.
///
/// Le détail porte une décision : un fichier que l'appareil ne sait pas lire
/// se rattrape par le transcodage du serveur, une source injoignable non.
enum OnyxApplePlayerErrorKind {
  unsupported,
  source,
  unknown,
}

/// Une piste qu'AetherEngine a énumérée.
class OnyxAppleTrack {
  OnyxAppleTrack({
    required this.id,
    this.title,
    this.language,
    required this.codec,
    required this.channels,
    required this.isDefault,
    required this.isForced,
    required this.isAtmos,
    required this.isBitmap,
    required this.isContainerStream,
  });

  /// L'index du flux dans le conteneur (`TrackInfo.id`), en texte : c'est ce
  /// que `PlaybackTrack.id` attend.
  String id;

  String? title;

  String? language;

  /// Le nom libavcodec : `truehd`, `hdmv_pgs_subtitle`…
  String codec;

  /// 0 pour une piste de sous-titres.
  int channels;

  bool isDefault;

  bool isForced;

  /// E-AC-3 JOC : le lit d'objets passe tel quel jusqu'à la sortie.
  bool isAtmos;

  /// Sous-titres image (PGS, VobSub, DVB), dessinés en bitmap.
  bool isBitmap;

  /// Un vrai flux du conteneur. Faux pour un sous-titre externe posé par
  /// l'app, et pour les sous-titres CEA-608 que le moteur extrait de l'image :
  /// ni l'un ni l'autre n'a de place dans la numérotation des pistes du
  /// fichier, par laquelle le contrôleur retrouve leur langue.
  bool isContainerStream;

  List<Object?> _toList() {
    return <Object?>[
      id,
      title,
      language,
      codec,
      channels,
      isDefault,
      isForced,
      isAtmos,
      isBitmap,
      isContainerStream,
    ];
  }

  Object encode() {
    return _toList();  }

  static OnyxAppleTrack decode(Object result) {
    result as List<Object?>;
    return OnyxAppleTrack(
      id: result[0]! as String,
      title: result[1] as String?,
      language: result[2] as String?,
      codec: result[3]! as String,
      channels: result[4]! as int,
      isDefault: result[5]! as bool,
      isForced: result[6]! as bool,
      isAtmos: result[7]! as bool,
      isBitmap: result[8]! as bool,
      isContainerStream: result[9]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OnyxAppleTrack || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) && _deepEquals(title, other.title) && _deepEquals(language, other.language) && _deepEquals(codec, other.codec) && _deepEquals(channels, other.channels) && _deepEquals(isDefault, other.isDefault) && _deepEquals(isForced, other.isForced) && _deepEquals(isAtmos, other.isAtmos) && _deepEquals(isBitmap, other.isBitmap) && _deepEquals(isContainerStream, other.isContainerStream);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'OnyxAppleTrack(id: $id, title: $title, language: $language, codec: $codec, channels: $channels, isDefault: $isDefault, isForced: $isForced, isAtmos: $isAtmos, isBitmap: $isBitmap, isContainerStream: $isContainerStream)';
  }
}

class OnyxAppleVideoSize {
  OnyxAppleVideoSize({
    required this.width,
    required this.height,
  });

  int width;

  int height;

  List<Object?> _toList() {
    return <Object?>[
      width,
      height,
    ];
  }

  Object encode() {
    return _toList();  }

  static OnyxAppleVideoSize decode(Object result) {
    result as List<Object?>;
    return OnyxAppleVideoSize(
      width: result[0]! as int,
      height: result[1]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OnyxAppleVideoSize || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(width, other.width) && _deepEquals(height, other.height);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'OnyxAppleVideoSize(width: $width, height: $height)';
  }
}

/// Un instantané complet de l'état du lecteur.
///
/// Un seul objet plutôt qu'un événement par propriété, comme sur Android :
/// l'appelant n'a qu'un état à réconcilier.
class OnyxApplePlayerStatus {
  OnyxApplePlayerStatus({
    required this.playerId,
    required this.state,
    required this.isPlaying,
    required this.positionMs,
    required this.durationMs,
    required this.bufferedPositionMs,
    this.videoSize,
    this.pixelAspectRatio,
    required this.audioTracks,
    required this.subtitleTracks,
    this.selectedAudioTrackId,
    this.selectedSubtitleTrackId,
    required this.videoFormat,
    this.errorKind,
    this.errorMessage,
  });

  int playerId;

  OnyxApplePlaybackState state;

  /// L'image avance réellement, distinct de « on lui a demandé de lire ».
  bool isPlaying;

  int positionMs;

  /// 0 tant que la sonde du conteneur n'a pas répondu.
  int durationMs;

  int bufferedPositionMs;

  /// Null tant que la sonde n'a pas donné les dimensions.
  OnyxAppleVideoSize? videoSize;

  /// Les pixels non carrés d'un DVD ou d'un MPEG-2 anamorphosé. Null quand ils
  /// sont carrés.
  double? pixelAspectRatio;

  List<OnyxAppleTrack> audioTracks;

  List<OnyxAppleTrack> subtitleTracks;

  String? selectedAudioTrackId;

  String? selectedSubtitleTrackId;

  /// Ce que l'écran présente : `sdr`, `hdr10`, `hdr10plus`, `dolbyvision`,
  /// `hlg`. Déjà ramené à ce que l'écran sait faire — un Dolby Vision sur un
  /// écran HDR10 se lit `hdr10`.
  String videoFormat;

  OnyxApplePlayerErrorKind? errorKind;

  String? errorMessage;

  List<Object?> _toList() {
    return <Object?>[
      playerId,
      state,
      isPlaying,
      positionMs,
      durationMs,
      bufferedPositionMs,
      videoSize,
      pixelAspectRatio,
      audioTracks,
      subtitleTracks,
      selectedAudioTrackId,
      selectedSubtitleTrackId,
      videoFormat,
      errorKind,
      errorMessage,
    ];
  }

  Object encode() {
    return _toList();  }

  static OnyxApplePlayerStatus decode(Object result) {
    result as List<Object?>;
    return OnyxApplePlayerStatus(
      playerId: result[0]! as int,
      state: result[1]! as OnyxApplePlaybackState,
      isPlaying: result[2]! as bool,
      positionMs: result[3]! as int,
      durationMs: result[4]! as int,
      bufferedPositionMs: result[5]! as int,
      videoSize: result[6] as OnyxAppleVideoSize?,
      pixelAspectRatio: result[7] as double?,
      audioTracks: (result[8]! as List<Object?>).cast<OnyxAppleTrack>(),
      subtitleTracks: (result[9]! as List<Object?>).cast<OnyxAppleTrack>(),
      selectedAudioTrackId: result[10] as String?,
      selectedSubtitleTrackId: result[11] as String?,
      videoFormat: result[12]! as String,
      errorKind: result[13] as OnyxApplePlayerErrorKind?,
      errorMessage: result[14] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OnyxApplePlayerStatus || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(playerId, other.playerId) && _deepEquals(state, other.state) && _deepEquals(isPlaying, other.isPlaying) && _deepEquals(positionMs, other.positionMs) && _deepEquals(durationMs, other.durationMs) && _deepEquals(bufferedPositionMs, other.bufferedPositionMs) && _deepEquals(videoSize, other.videoSize) && _deepEquals(pixelAspectRatio, other.pixelAspectRatio) && _deepEquals(audioTracks, other.audioTracks) && _deepEquals(subtitleTracks, other.subtitleTracks) && _deepEquals(selectedAudioTrackId, other.selectedAudioTrackId) && _deepEquals(selectedSubtitleTrackId, other.selectedSubtitleTrackId) && _deepEquals(videoFormat, other.videoFormat) && _deepEquals(errorKind, other.errorKind) && _deepEquals(errorMessage, other.errorMessage);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'OnyxApplePlayerStatus(playerId: $playerId, state: $state, isPlaying: $isPlaying, positionMs: $positionMs, durationMs: $durationMs, bufferedPositionMs: $bufferedPositionMs, videoSize: $videoSize, pixelAspectRatio: $pixelAspectRatio, audioTracks: $audioTracks, subtitleTracks: $subtitleTracks, selectedAudioTrackId: $selectedAudioTrackId, selectedSubtitleTrackId: $selectedSubtitleTrackId, videoFormat: $videoFormat, errorKind: $errorKind, errorMessage: $errorMessage)';
  }
}

/// Un sous-titre image, placé en fractions de l'image vidéo.
///
/// Les fractions et non des pixels : la vue Flutter qui le peint n'a pas la
/// taille du canevas du PGS, et c'est elle qui sait où est l'image à l'écran.
class OnyxAppleSubtitleBitmap {
  OnyxAppleSubtitleBitmap({
    required this.png,
    required this.left,
    required this.top,
    required this.width,
    required this.height,
  });

  Uint8List png;

  double left;

  double top;

  double width;

  double height;

  List<Object?> _toList() {
    return <Object?>[
      png,
      left,
      top,
      width,
      height,
    ];
  }

  Object encode() {
    return _toList();  }

  static OnyxAppleSubtitleBitmap decode(Object result) {
    result as List<Object?>;
    return OnyxAppleSubtitleBitmap(
      png: result[0]! as Uint8List,
      left: result[1]! as double,
      top: result[2]! as double,
      width: result[3]! as double,
      height: result[4]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OnyxAppleSubtitleBitmap || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(png, other.png) && _deepEquals(left, other.left) && _deepEquals(top, other.top) && _deepEquals(width, other.width) && _deepEquals(height, other.height);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'OnyxAppleSubtitleBitmap(png: $png, left: $left, top: $top, width: $width, height: $height)';
  }
}

/// Ce qu'il faut afficher comme sous-titres à cet instant.
///
/// Un flux à part du statut : il ne change qu'à chaque réplique, et une image
/// PGS n'a rien à faire dans un événement qui part quatre fois par seconde.
class OnyxAppleSubtitleFrame {
  OnyxAppleSubtitleFrame({
    required this.playerId,
    required this.lines,
    required this.bitmaps,
  });

  int playerId;

  /// Les répliques texte, à peindre par la couche de sous-titres de l'app
  /// pour garder le même habillage partout.
  List<String> lines;

  List<OnyxAppleSubtitleBitmap> bitmaps;

  List<Object?> _toList() {
    return <Object?>[
      playerId,
      lines,
      bitmaps,
    ];
  }

  Object encode() {
    return _toList();  }

  static OnyxAppleSubtitleFrame decode(Object result) {
    result as List<Object?>;
    return OnyxAppleSubtitleFrame(
      playerId: result[0]! as int,
      lines: (result[1]! as List<Object?>).cast<String>(),
      bitmaps: (result[2]! as List<Object?>).cast<OnyxAppleSubtitleBitmap>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OnyxAppleSubtitleFrame || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(playerId, other.playerId) && _deepEquals(lines, other.lines) && _deepEquals(bitmaps, other.bitmaps);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'OnyxAppleSubtitleFrame(playerId: $playerId, lines: $lines, bitmaps: $bitmaps)';
  }
}

/// Ce qu'AetherEngine sait dire de la lecture en cours, pour le journal.
class OnyxApplePlaybackStats {
  OnyxApplePlaybackStats({
    this.droppedFrames,
    this.observedFps,
    this.containerFps,
    this.videoCodec,
    this.videoDecoder,
    this.audioDecoder,
    this.videoBitrate,
    this.averageBitrateMbps,
    this.route,
    this.audioDelivery,
    this.container,
  });

  int? droppedFrames;

  double? observedFps;

  double? containerFps;

  String? videoCodec;

  String? videoDecoder;

  String? audioDecoder;

  /// Ce que le conteneur déclare, en bits par seconde.
  int? videoBitrate;

  /// Ce qui a réellement transité depuis l'ouverture.
  double? averageBitrateMbps;

  /// Le chemin qui sert la lecture : `loopback` (AVPlayer sur un remux local),
  /// `software` (décodage FFmpeg), `remoteBypass` (HLS du serveur lu tel
  /// quel). C'est la première chose à savoir d'une lecture qui chauffe.
  String? route;

  /// `streamCopy`, `bridged`, `decoded`… : l'audio est-il passé tel quel.
  String? audioDelivery;

  String? container;

  List<Object?> _toList() {
    return <Object?>[
      droppedFrames,
      observedFps,
      containerFps,
      videoCodec,
      videoDecoder,
      audioDecoder,
      videoBitrate,
      averageBitrateMbps,
      route,
      audioDelivery,
      container,
    ];
  }

  Object encode() {
    return _toList();  }

  static OnyxApplePlaybackStats decode(Object result) {
    result as List<Object?>;
    return OnyxApplePlaybackStats(
      droppedFrames: result[0] as int?,
      observedFps: result[1] as double?,
      containerFps: result[2] as double?,
      videoCodec: result[3] as String?,
      videoDecoder: result[4] as String?,
      audioDecoder: result[5] as String?,
      videoBitrate: result[6] as int?,
      averageBitrateMbps: result[7] as double?,
      route: result[8] as String?,
      audioDelivery: result[9] as String?,
      container: result[10] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OnyxApplePlaybackStats || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(droppedFrames, other.droppedFrames) && _deepEquals(observedFps, other.observedFps) && _deepEquals(containerFps, other.containerFps) && _deepEquals(videoCodec, other.videoCodec) && _deepEquals(videoDecoder, other.videoDecoder) && _deepEquals(audioDecoder, other.audioDecoder) && _deepEquals(videoBitrate, other.videoBitrate) && _deepEquals(averageBitrateMbps, other.averageBitrateMbps) && _deepEquals(route, other.route) && _deepEquals(audioDelivery, other.audioDelivery) && _deepEquals(container, other.container);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'OnyxApplePlaybackStats(droppedFrames: $droppedFrames, observedFps: $observedFps, containerFps: $containerFps, videoCodec: $videoCodec, videoDecoder: $videoDecoder, audioDecoder: $audioDecoder, videoBitrate: $videoBitrate, averageBitrateMbps: $averageBitrateMbps, route: $route, audioDelivery: $audioDelivery, container: $container)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is OnyxApplePlaybackState) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is OnyxApplePlayerErrorKind) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is OnyxAppleTrack) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is OnyxAppleVideoSize) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is OnyxApplePlayerStatus) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is OnyxAppleSubtitleBitmap) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is OnyxAppleSubtitleFrame) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is OnyxApplePlaybackStats) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : OnyxApplePlaybackState.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : OnyxApplePlayerErrorKind.values[value];
      case 131:
        return OnyxAppleTrack.decode(readValue(buffer)!);
      case 132:
        return OnyxAppleVideoSize.decode(readValue(buffer)!);
      case 133:
        return OnyxApplePlayerStatus.decode(readValue(buffer)!);
      case 134:
        return OnyxAppleSubtitleBitmap.decode(readValue(buffer)!);
      case 135:
        return OnyxAppleSubtitleFrame.decode(readValue(buffer)!);
      case 136:
        return OnyxApplePlaybackStats.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

const StandardMethodCodec pigeonMethodCodec = StandardMethodCodec(_PigeonCodec());

class OnyxApplePlayerApi {
  /// Constructor for [OnyxApplePlayerApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  OnyxApplePlayerApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Crée un lecteur et rend son identifiant. La vue s'y rattache par cet
  /// identifiant, ce qui permet d'ouvrir un média avant que la vue n'existe
  /// et de survivre à sa reconstruction.
  Future<int> create() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onyx_player_apple.OnyxApplePlayerApi.create$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }

  /// Détruit le lecteur. Sans appel, AetherEngine garde sa connexion, son
  /// serveur local et son décodeur pour toute la vie du processus.
  Future<void> release(int playerId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onyx_player_apple.OnyxApplePlayerApi.release$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[playerId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Charge [url] (le fichier du serveur, un fichier téléchargé ou une
  /// session HLS) en se plaçant à [startPositionMs] dans le même geste.
  ///
  /// Rend la main tout de suite : l'ouverture et ses pannes arrivent par le
  /// flux d'état, comme sur Android.
  Future<void> open(int playerId, String url, int startPositionMs, bool play) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onyx_player_apple.OnyxApplePlayerApi.open$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[playerId, url, startPositionMs, play]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> play(int playerId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onyx_player_apple.OnyxApplePlayerApi.play$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[playerId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> pause(int playerId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onyx_player_apple.OnyxApplePlayerApi.pause$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[playerId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> seekTo(int playerId, int positionMs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onyx_player_apple.OnyxApplePlayerApi.seekTo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[playerId, positionMs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Décharge le média sans détruire le lecteur.
  Future<void> stop(int playerId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onyx_player_apple.OnyxApplePlayerApi.stop$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[playerId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> setVolume(int playerId, double volume) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onyx_player_apple.OnyxApplePlayerApi.setVolume$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[playerId, volume]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> setRate(int playerId, double rate) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onyx_player_apple.OnyxApplePlayerApi.setRate$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[playerId, rate]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Quelle langue audio charger d'emblée, la plus probable en premier. Posé
  /// avant l'ouverture : après, changer de piste reconstruit la session
  /// (une demi-seconde d'image noire).
  Future<void> setPreferredAudioLanguages(int playerId, List<String> priorities) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onyx_player_apple.OnyxApplePlayerApi.setPreferredAudioLanguages$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[playerId, priorities]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> selectAudioTrack(int playerId, String trackId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onyx_player_apple.OnyxApplePlayerApi.selectAudioTrack$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[playerId, trackId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Une piste de sous-titres du média, ou aucune si [trackId] est nul.
  Future<void> selectSubtitleTrack(int playerId, String? trackId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onyx_player_apple.OnyxApplePlayerApi.selectSubtitleTrack$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[playerId, trackId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Pose (ou retire, avec null) le WebVTT que le serveur a produit.
  Future<void> setExternalSubtitle(int playerId, String? vttContent, String? language, String? title) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onyx_player_apple.OnyxApplePlayerApi.setExternalSubtitle$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[playerId, vttContent, language, title]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// L'état à cet instant, pour s'amorcer sans attendre le premier événement.
  Future<OnyxApplePlayerStatus> status(int playerId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onyx_player_apple.OnyxApplePlayerApi.status$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[playerId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as OnyxApplePlayerStatus;
  }

  Future<OnyxApplePlaybackStats> stats(int playerId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onyx_player_apple.OnyxApplePlayerApi.stats$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[playerId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as OnyxApplePlaybackStats;
  }
}

/// Un flux unique pour tous les lecteurs ; [OnyxApplePlayerStatus.playerId]
/// dit lequel.
///
/// Returns a broadcast [Stream] of events from the `statusChanged` event channel.
///
/// Each call to this method creates a new [EventChannel], so it should
/// not be called multiple times for the same `instanceName`. To deliver
/// events to multiple listeners, call this method once and listen to the
/// returned broadcast stream multiple times instead.
Stream<OnyxApplePlayerStatus> statusChanged( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel statusChangedChannel =
      EventChannel('dev.flutter.pigeon.onyx_player_apple.OnyxApplePlayerEventApi.statusChanged$instanceName', pigeonMethodCodec);
  return statusChangedChannel.receiveBroadcastStream().map((dynamic event) {
    return event as OnyxApplePlayerStatus;
  });
}
    
/// Les sous-titres à afficher, à chaque changement de réplique.
///
/// Returns a broadcast [Stream] of events from the `subtitlesChanged` event channel.
///
/// Each call to this method creates a new [EventChannel], so it should
/// not be called multiple times for the same `instanceName`. To deliver
/// events to multiple listeners, call this method once and listen to the
/// returned broadcast stream multiple times instead.
Stream<OnyxAppleSubtitleFrame> subtitlesChanged( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel subtitlesChangedChannel =
      EventChannel('dev.flutter.pigeon.onyx_player_apple.OnyxApplePlayerEventApi.subtitlesChanged$instanceName', pigeonMethodCodec);
  return subtitlesChangedChannel.receiveBroadcastStream().map((dynamic event) {
    return event as OnyxAppleSubtitleFrame;
  });
}
    
/// Le journal d'AetherEngine, par paquets de lignes, pour le journal par
/// lecture de l'app (ADR-0026). Les secrets (ticket de lecture) y sont
/// déjà masqués.
///
/// Returns a broadcast [Stream] of events from the `engineLog` event channel.
///
/// Each call to this method creates a new [EventChannel], so it should
/// not be called multiple times for the same `instanceName`. To deliver
/// events to multiple listeners, call this method once and listen to the
/// returned broadcast stream multiple times instead.
Stream<List> engineLog( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel engineLogChannel =
      EventChannel('dev.flutter.pigeon.onyx_player_apple.OnyxApplePlayerEventApi.engineLog$instanceName', pigeonMethodCodec);
  return engineLogChannel.receiveBroadcastStream().map((dynamic event) {
    return event as List;
  });
}
    
