// Autogenerated from Pigeon (v28.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS) || os(tvOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Où en est le lecteur. Le même vocabulaire que sur Android, pour que les
/// deux sessions de l'app se lisent de la même façon.
enum OnyxApplePlaybackState: Int, CaseIterable {
  /// Rien de chargé, ou lecture arrêtée.
  case idle = 0
  /// Ouverture, saut ou réserve vide : l'image n'avance pas en attendant des
  /// données.
  case buffering = 1
  /// Prêt à jouer, ou en train de jouer.
  case ready = 2
  /// Arrivé au bout. Terminal : il faut rouvrir pour relire.
  case ended = 3
}

/// Pourquoi une ouverture a échoué.
///
/// Le détail porte une décision : un fichier que l'appareil ne sait pas lire
/// se rattrape par le transcodage du serveur, une source injoignable non.
enum OnyxApplePlayerErrorKind: Int, CaseIterable {
  case unsupported = 0
  case source = 1
  case unknown = 2
}

/// Une piste qu'AetherEngine a énumérée.
///
/// Generated class from Pigeon that represents data sent in messages.
struct OnyxAppleTrack: Hashable, CustomStringConvertible {
  /// L'index du flux dans le conteneur (`TrackInfo.id`), en texte : c'est ce
  /// que `PlaybackTrack.id` attend.
  var id: String
  var title: String? = nil
  var language: String? = nil
  /// Le nom libavcodec : `truehd`, `hdmv_pgs_subtitle`…
  var codec: String
  /// 0 pour une piste de sous-titres.
  var channels: Int64
  var isDefault: Bool
  var isForced: Bool
  /// E-AC-3 JOC : le lit d'objets passe tel quel jusqu'à la sortie.
  var isAtmos: Bool
  /// Sous-titres image (PGS, VobSub, DVB), dessinés en bitmap.
  var isBitmap: Bool
  /// Un vrai flux du conteneur. Faux pour un sous-titre externe posé par
  /// l'app, et pour les sous-titres CEA-608 que le moteur extrait de l'image :
  /// ni l'un ni l'autre n'a de place dans la numérotation des pistes du
  /// fichier, par laquelle le contrôleur retrouve leur langue.
  var isContainerStream: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> OnyxAppleTrack? {
    let id = pigeonVar_list[0] as! String
    let title: String? = nilOrValue(pigeonVar_list[1])
    let language: String? = nilOrValue(pigeonVar_list[2])
    let codec = pigeonVar_list[3] as! String
    let channels = pigeonVar_list[4] as! Int64
    let isDefault = pigeonVar_list[5] as! Bool
    let isForced = pigeonVar_list[6] as! Bool
    let isAtmos = pigeonVar_list[7] as! Bool
    let isBitmap = pigeonVar_list[8] as! Bool
    let isContainerStream = pigeonVar_list[9] as! Bool

    return OnyxAppleTrack(
      id: id,
      title: title,
      language: language,
      codec: codec,
      channels: channels,
      isDefault: isDefault,
      isForced: isForced,
      isAtmos: isAtmos,
      isBitmap: isBitmap,
      isContainerStream: isContainerStream
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      title,
      language,
      codec,
      channels,
      isDefault,
      isForced,
      isAtmos,
      isBitmap,
      isContainerStream,
    ]
  }
  static func == (lhs: OnyxAppleTrack, rhs: OnyxAppleTrack) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.id, rhs.id) && MessagesPigeonInternal.deepEquals(lhs.title, rhs.title) && MessagesPigeonInternal.deepEquals(lhs.language, rhs.language) && MessagesPigeonInternal.deepEquals(lhs.codec, rhs.codec) && MessagesPigeonInternal.deepEquals(lhs.channels, rhs.channels) && MessagesPigeonInternal.deepEquals(lhs.isDefault, rhs.isDefault) && MessagesPigeonInternal.deepEquals(lhs.isForced, rhs.isForced) && MessagesPigeonInternal.deepEquals(lhs.isAtmos, rhs.isAtmos) && MessagesPigeonInternal.deepEquals(lhs.isBitmap, rhs.isBitmap) && MessagesPigeonInternal.deepEquals(lhs.isContainerStream, rhs.isContainerStream)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("OnyxAppleTrack")
    MessagesPigeonInternal.deepHash(value: id, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: title, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: language, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: codec, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: channels, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: isDefault, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: isForced, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: isAtmos, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: isBitmap, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: isContainerStream, hasher: &hasher)
  }

  public var description: String {
    return "OnyxAppleTrack(id: \(String(describing: id)), title: \(String(describing: title)), language: \(String(describing: language)), codec: \(String(describing: codec)), channels: \(String(describing: channels)), isDefault: \(String(describing: isDefault)), isForced: \(String(describing: isForced)), isAtmos: \(String(describing: isAtmos)), isBitmap: \(String(describing: isBitmap)), isContainerStream: \(String(describing: isContainerStream)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct OnyxAppleVideoSize: Hashable, CustomStringConvertible {
  var width: Int64
  var height: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> OnyxAppleVideoSize? {
    let width = pigeonVar_list[0] as! Int64
    let height = pigeonVar_list[1] as! Int64

    return OnyxAppleVideoSize(
      width: width,
      height: height
    )
  }
  func toList() -> [Any?] {
    return [
      width,
      height,
    ]
  }
  static func == (lhs: OnyxAppleVideoSize, rhs: OnyxAppleVideoSize) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.width, rhs.width) && MessagesPigeonInternal.deepEquals(lhs.height, rhs.height)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("OnyxAppleVideoSize")
    MessagesPigeonInternal.deepHash(value: width, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: height, hasher: &hasher)
  }

  public var description: String {
    return "OnyxAppleVideoSize(width: \(String(describing: width)), height: \(String(describing: height)))"
  }
}

/// Un instantané complet de l'état du lecteur.
///
/// Un seul objet plutôt qu'un événement par propriété, comme sur Android :
/// l'appelant n'a qu'un état à réconcilier.
///
/// Generated class from Pigeon that represents data sent in messages.
struct OnyxApplePlayerStatus: Hashable, CustomStringConvertible {
  var playerId: Int64
  var state: OnyxApplePlaybackState
  /// L'image avance réellement, distinct de « on lui a demandé de lire ».
  var isPlaying: Bool
  var positionMs: Int64
  /// 0 tant que la sonde du conteneur n'a pas répondu.
  var durationMs: Int64
  var bufferedPositionMs: Int64
  /// Null tant que la sonde n'a pas donné les dimensions.
  var videoSize: OnyxAppleVideoSize? = nil
  /// Les pixels non carrés d'un DVD ou d'un MPEG-2 anamorphosé. Null quand ils
  /// sont carrés.
  var pixelAspectRatio: Double? = nil
  var audioTracks: [OnyxAppleTrack]
  var subtitleTracks: [OnyxAppleTrack]
  var selectedAudioTrackId: String? = nil
  var selectedSubtitleTrackId: String? = nil
  /// Ce que l'écran présente : `sdr`, `hdr10`, `hdr10plus`, `dolbyvision`,
  /// `hlg`. Déjà ramené à ce que l'écran sait faire — un Dolby Vision sur un
  /// écran HDR10 se lit `hdr10`.
  var videoFormat: String
  var errorKind: OnyxApplePlayerErrorKind? = nil
  var errorMessage: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> OnyxApplePlayerStatus? {
    let playerId = pigeonVar_list[0] as! Int64
    let state = pigeonVar_list[1] as! OnyxApplePlaybackState
    let isPlaying = pigeonVar_list[2] as! Bool
    let positionMs = pigeonVar_list[3] as! Int64
    let durationMs = pigeonVar_list[4] as! Int64
    let bufferedPositionMs = pigeonVar_list[5] as! Int64
    let videoSize: OnyxAppleVideoSize? = nilOrValue(pigeonVar_list[6])
    let pixelAspectRatio: Double? = nilOrValue(pigeonVar_list[7])
    let audioTracks = pigeonVar_list[8] as! [OnyxAppleTrack]
    let subtitleTracks = pigeonVar_list[9] as! [OnyxAppleTrack]
    let selectedAudioTrackId: String? = nilOrValue(pigeonVar_list[10])
    let selectedSubtitleTrackId: String? = nilOrValue(pigeonVar_list[11])
    let videoFormat = pigeonVar_list[12] as! String
    let errorKind: OnyxApplePlayerErrorKind? = nilOrValue(pigeonVar_list[13])
    let errorMessage: String? = nilOrValue(pigeonVar_list[14])

    return OnyxApplePlayerStatus(
      playerId: playerId,
      state: state,
      isPlaying: isPlaying,
      positionMs: positionMs,
      durationMs: durationMs,
      bufferedPositionMs: bufferedPositionMs,
      videoSize: videoSize,
      pixelAspectRatio: pixelAspectRatio,
      audioTracks: audioTracks,
      subtitleTracks: subtitleTracks,
      selectedAudioTrackId: selectedAudioTrackId,
      selectedSubtitleTrackId: selectedSubtitleTrackId,
      videoFormat: videoFormat,
      errorKind: errorKind,
      errorMessage: errorMessage
    )
  }
  func toList() -> [Any?] {
    return [
      playerId,
      state,
      isPlaying,
      positionMs,
      durationMs,
      bufferedPositionMs,
      videoSize,
      pixelAspectRatio,
      audioTracks,
      subtitleTracks,
      selectedAudioTrackId,
      selectedSubtitleTrackId,
      videoFormat,
      errorKind,
      errorMessage,
    ]
  }
  static func == (lhs: OnyxApplePlayerStatus, rhs: OnyxApplePlayerStatus) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.playerId, rhs.playerId) && MessagesPigeonInternal.deepEquals(lhs.state, rhs.state) && MessagesPigeonInternal.deepEquals(lhs.isPlaying, rhs.isPlaying) && MessagesPigeonInternal.deepEquals(lhs.positionMs, rhs.positionMs) && MessagesPigeonInternal.deepEquals(lhs.durationMs, rhs.durationMs) && MessagesPigeonInternal.deepEquals(lhs.bufferedPositionMs, rhs.bufferedPositionMs) && MessagesPigeonInternal.deepEquals(lhs.videoSize, rhs.videoSize) && MessagesPigeonInternal.deepEquals(lhs.pixelAspectRatio, rhs.pixelAspectRatio) && MessagesPigeonInternal.deepEquals(lhs.audioTracks, rhs.audioTracks) && MessagesPigeonInternal.deepEquals(lhs.subtitleTracks, rhs.subtitleTracks) && MessagesPigeonInternal.deepEquals(lhs.selectedAudioTrackId, rhs.selectedAudioTrackId) && MessagesPigeonInternal.deepEquals(lhs.selectedSubtitleTrackId, rhs.selectedSubtitleTrackId) && MessagesPigeonInternal.deepEquals(lhs.videoFormat, rhs.videoFormat) && MessagesPigeonInternal.deepEquals(lhs.errorKind, rhs.errorKind) && MessagesPigeonInternal.deepEquals(lhs.errorMessage, rhs.errorMessage)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("OnyxApplePlayerStatus")
    MessagesPigeonInternal.deepHash(value: playerId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: state, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: isPlaying, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: positionMs, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: durationMs, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: bufferedPositionMs, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: videoSize, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: pixelAspectRatio, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: audioTracks, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: subtitleTracks, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: selectedAudioTrackId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: selectedSubtitleTrackId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: videoFormat, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: errorKind, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: errorMessage, hasher: &hasher)
  }

  public var description: String {
    return "OnyxApplePlayerStatus(playerId: \(String(describing: playerId)), state: \(String(describing: state)), isPlaying: \(String(describing: isPlaying)), positionMs: \(String(describing: positionMs)), durationMs: \(String(describing: durationMs)), bufferedPositionMs: \(String(describing: bufferedPositionMs)), videoSize: \(String(describing: videoSize)), pixelAspectRatio: \(String(describing: pixelAspectRatio)), audioTracks: \(String(describing: audioTracks)), subtitleTracks: \(String(describing: subtitleTracks)), selectedAudioTrackId: \(String(describing: selectedAudioTrackId)), selectedSubtitleTrackId: \(String(describing: selectedSubtitleTrackId)), videoFormat: \(String(describing: videoFormat)), errorKind: \(String(describing: errorKind)), errorMessage: \(String(describing: errorMessage)))"
  }
}

/// Un sous-titre image, placé en fractions de l'image vidéo.
///
/// Les fractions et non des pixels : la vue Flutter qui le peint n'a pas la
/// taille du canevas du PGS, et c'est elle qui sait où est l'image à l'écran.
///
/// Generated class from Pigeon that represents data sent in messages.
struct OnyxAppleSubtitleBitmap: Hashable, CustomStringConvertible {
  var png: FlutterStandardTypedData
  var left: Double
  var top: Double
  var width: Double
  var height: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> OnyxAppleSubtitleBitmap? {
    let png = pigeonVar_list[0] as! FlutterStandardTypedData
    let left = pigeonVar_list[1] as! Double
    let top = pigeonVar_list[2] as! Double
    let width = pigeonVar_list[3] as! Double
    let height = pigeonVar_list[4] as! Double

    return OnyxAppleSubtitleBitmap(
      png: png,
      left: left,
      top: top,
      width: width,
      height: height
    )
  }
  func toList() -> [Any?] {
    return [
      png,
      left,
      top,
      width,
      height,
    ]
  }
  static func == (lhs: OnyxAppleSubtitleBitmap, rhs: OnyxAppleSubtitleBitmap) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.png, rhs.png) && MessagesPigeonInternal.deepEquals(lhs.left, rhs.left) && MessagesPigeonInternal.deepEquals(lhs.top, rhs.top) && MessagesPigeonInternal.deepEquals(lhs.width, rhs.width) && MessagesPigeonInternal.deepEquals(lhs.height, rhs.height)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("OnyxAppleSubtitleBitmap")
    MessagesPigeonInternal.deepHash(value: png, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: left, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: top, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: width, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: height, hasher: &hasher)
  }

  public var description: String {
    return "OnyxAppleSubtitleBitmap(png: \(String(describing: png)), left: \(String(describing: left)), top: \(String(describing: top)), width: \(String(describing: width)), height: \(String(describing: height)))"
  }
}

/// Ce qu'il faut afficher comme sous-titres à cet instant.
///
/// Un flux à part du statut : il ne change qu'à chaque réplique, et une image
/// PGS n'a rien à faire dans un événement qui part quatre fois par seconde.
///
/// Generated class from Pigeon that represents data sent in messages.
struct OnyxAppleSubtitleFrame: Hashable, CustomStringConvertible {
  var playerId: Int64
  /// Les répliques texte, à peindre par la couche de sous-titres de l'app
  /// pour garder le même habillage partout.
  var lines: [String]
  var bitmaps: [OnyxAppleSubtitleBitmap]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> OnyxAppleSubtitleFrame? {
    let playerId = pigeonVar_list[0] as! Int64
    let lines = pigeonVar_list[1] as! [String]
    let bitmaps = pigeonVar_list[2] as! [OnyxAppleSubtitleBitmap]

    return OnyxAppleSubtitleFrame(
      playerId: playerId,
      lines: lines,
      bitmaps: bitmaps
    )
  }
  func toList() -> [Any?] {
    return [
      playerId,
      lines,
      bitmaps,
    ]
  }
  static func == (lhs: OnyxAppleSubtitleFrame, rhs: OnyxAppleSubtitleFrame) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.playerId, rhs.playerId) && MessagesPigeonInternal.deepEquals(lhs.lines, rhs.lines) && MessagesPigeonInternal.deepEquals(lhs.bitmaps, rhs.bitmaps)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("OnyxAppleSubtitleFrame")
    MessagesPigeonInternal.deepHash(value: playerId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: lines, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: bitmaps, hasher: &hasher)
  }

  public var description: String {
    return "OnyxAppleSubtitleFrame(playerId: \(String(describing: playerId)), lines: \(String(describing: lines)), bitmaps: \(String(describing: bitmaps)))"
  }
}

/// Ce qu'AetherEngine sait dire de la lecture en cours, pour le journal.
///
/// Generated class from Pigeon that represents data sent in messages.
struct OnyxApplePlaybackStats: Hashable, CustomStringConvertible {
  var droppedFrames: Int64? = nil
  var observedFps: Double? = nil
  var containerFps: Double? = nil
  var videoCodec: String? = nil
  var videoDecoder: String? = nil
  var audioDecoder: String? = nil
  /// Ce que le conteneur déclare, en bits par seconde.
  var videoBitrate: Int64? = nil
  /// Ce qui a réellement transité depuis l'ouverture.
  var averageBitrateMbps: Double? = nil
  /// Le chemin qui sert la lecture : `loopback` (AVPlayer sur un remux local),
  /// `software` (décodage FFmpeg), `remoteBypass` (HLS du serveur lu tel
  /// quel). C'est la première chose à savoir d'une lecture qui chauffe.
  var route: String? = nil
  /// `streamCopy`, `bridged`, `decoded`… : l'audio est-il passé tel quel.
  var audioDelivery: String? = nil
  var container: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> OnyxApplePlaybackStats? {
    let droppedFrames: Int64? = nilOrValue(pigeonVar_list[0])
    let observedFps: Double? = nilOrValue(pigeonVar_list[1])
    let containerFps: Double? = nilOrValue(pigeonVar_list[2])
    let videoCodec: String? = nilOrValue(pigeonVar_list[3])
    let videoDecoder: String? = nilOrValue(pigeonVar_list[4])
    let audioDecoder: String? = nilOrValue(pigeonVar_list[5])
    let videoBitrate: Int64? = nilOrValue(pigeonVar_list[6])
    let averageBitrateMbps: Double? = nilOrValue(pigeonVar_list[7])
    let route: String? = nilOrValue(pigeonVar_list[8])
    let audioDelivery: String? = nilOrValue(pigeonVar_list[9])
    let container: String? = nilOrValue(pigeonVar_list[10])

    return OnyxApplePlaybackStats(
      droppedFrames: droppedFrames,
      observedFps: observedFps,
      containerFps: containerFps,
      videoCodec: videoCodec,
      videoDecoder: videoDecoder,
      audioDecoder: audioDecoder,
      videoBitrate: videoBitrate,
      averageBitrateMbps: averageBitrateMbps,
      route: route,
      audioDelivery: audioDelivery,
      container: container
    )
  }
  func toList() -> [Any?] {
    return [
      droppedFrames,
      observedFps,
      containerFps,
      videoCodec,
      videoDecoder,
      audioDecoder,
      videoBitrate,
      averageBitrateMbps,
      route,
      audioDelivery,
      container,
    ]
  }
  static func == (lhs: OnyxApplePlaybackStats, rhs: OnyxApplePlaybackStats) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.droppedFrames, rhs.droppedFrames) && MessagesPigeonInternal.deepEquals(lhs.observedFps, rhs.observedFps) && MessagesPigeonInternal.deepEquals(lhs.containerFps, rhs.containerFps) && MessagesPigeonInternal.deepEquals(lhs.videoCodec, rhs.videoCodec) && MessagesPigeonInternal.deepEquals(lhs.videoDecoder, rhs.videoDecoder) && MessagesPigeonInternal.deepEquals(lhs.audioDecoder, rhs.audioDecoder) && MessagesPigeonInternal.deepEquals(lhs.videoBitrate, rhs.videoBitrate) && MessagesPigeonInternal.deepEquals(lhs.averageBitrateMbps, rhs.averageBitrateMbps) && MessagesPigeonInternal.deepEquals(lhs.route, rhs.route) && MessagesPigeonInternal.deepEquals(lhs.audioDelivery, rhs.audioDelivery) && MessagesPigeonInternal.deepEquals(lhs.container, rhs.container)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("OnyxApplePlaybackStats")
    MessagesPigeonInternal.deepHash(value: droppedFrames, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: observedFps, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: containerFps, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: videoCodec, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: videoDecoder, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: audioDecoder, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: videoBitrate, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: averageBitrateMbps, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: route, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: audioDelivery, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: container, hasher: &hasher)
  }

  public var description: String {
    return "OnyxApplePlaybackStats(droppedFrames: \(String(describing: droppedFrames)), observedFps: \(String(describing: observedFps)), containerFps: \(String(describing: containerFps)), videoCodec: \(String(describing: videoCodec)), videoDecoder: \(String(describing: videoDecoder)), audioDecoder: \(String(describing: audioDecoder)), videoBitrate: \(String(describing: videoBitrate)), averageBitrateMbps: \(String(describing: averageBitrateMbps)), route: \(String(describing: route)), audioDelivery: \(String(describing: audioDelivery)), container: \(String(describing: container)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return OnyxApplePlaybackState(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return OnyxApplePlayerErrorKind(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return OnyxAppleTrack.fromList(self.readValue() as! [Any?])
    case 132:
      return OnyxAppleVideoSize.fromList(self.readValue() as! [Any?])
    case 133:
      return OnyxApplePlayerStatus.fromList(self.readValue() as! [Any?])
    case 134:
      return OnyxAppleSubtitleBitmap.fromList(self.readValue() as! [Any?])
    case 135:
      return OnyxAppleSubtitleFrame.fromList(self.readValue() as! [Any?])
    case 136:
      return OnyxApplePlaybackStats.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? OnyxApplePlaybackState {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? OnyxApplePlayerErrorKind {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? OnyxAppleTrack {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? OnyxAppleVideoSize {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? OnyxApplePlayerStatus {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? OnyxAppleSubtitleBitmap {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? OnyxAppleSubtitleFrame {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? OnyxApplePlaybackStats {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}

var messagesPigeonMethodCodec = FlutterStandardMethodCodec(readerWriter: MessagesPigeonCodecReaderWriter());

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol OnyxApplePlayerApi {
  /// Crée un lecteur et rend son identifiant. La vue s'y rattache par cet
  /// identifiant, ce qui permet d'ouvrir un média avant que la vue n'existe
  /// et de survivre à sa reconstruction.
  func create() throws -> Int64
  /// Détruit le lecteur. Sans appel, AetherEngine garde sa connexion, son
  /// serveur local et son décodeur pour toute la vie du processus.
  func release(playerId: Int64) throws
  /// Charge [url] (le fichier du serveur, un fichier téléchargé ou une
  /// session HLS) en se plaçant à [startPositionMs] dans le même geste.
  ///
  /// Rend la main tout de suite : l'ouverture et ses pannes arrivent par le
  /// flux d'état, comme sur Android.
  func open(playerId: Int64, url: String, startPositionMs: Int64, play: Bool) throws
  func play(playerId: Int64) throws
  func pause(playerId: Int64) throws
  func seekTo(playerId: Int64, positionMs: Int64) throws
  /// Décharge le média sans détruire le lecteur.
  func stop(playerId: Int64) throws
  func setVolume(playerId: Int64, volume: Double) throws
  func setRate(playerId: Int64, rate: Double) throws
  /// Quelle langue audio charger d'emblée, la plus probable en premier. Posé
  /// avant l'ouverture : après, changer de piste reconstruit la session
  /// (une demi-seconde d'image noire).
  func setPreferredAudioLanguages(playerId: Int64, priorities: [String]) throws
  func selectAudioTrack(playerId: Int64, trackId: String) throws
  /// Une piste de sous-titres du média, ou aucune si [trackId] est nul.
  func selectSubtitleTrack(playerId: Int64, trackId: String?) throws
  /// Pose (ou retire, avec null) le WebVTT que le serveur a produit.
  func setExternalSubtitle(playerId: Int64, vttContent: String?, language: String?, title: String?) throws
  /// L'état à cet instant, pour s'amorcer sans attendre le premier événement.
  func status(playerId: Int64) throws -> OnyxApplePlayerStatus
  func stats(playerId: Int64) throws -> OnyxApplePlaybackStats
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class OnyxApplePlayerApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `OnyxApplePlayerApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: OnyxApplePlayerApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Crée un lecteur et rend son identifiant. La vue s'y rattache par cet
    /// identifiant, ce qui permet d'ouvrir un média avant que la vue n'existe
    /// et de survivre à sa reconstruction.
    let createChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.onyx_player_apple.OnyxApplePlayerApi.create\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createChannel.setMessageHandler { _, reply in
        do {
          let result = try api.create()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      createChannel.setMessageHandler(nil)
    }
    /// Détruit le lecteur. Sans appel, AetherEngine garde sa connexion, son
    /// serveur local et son décodeur pour toute la vie du processus.
    let releaseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.onyx_player_apple.OnyxApplePlayerApi.release\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      releaseChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        do {
          try api.release(playerId: playerIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      releaseChannel.setMessageHandler(nil)
    }
    /// Charge [url] (le fichier du serveur, un fichier téléchargé ou une
    /// session HLS) en se plaçant à [startPositionMs] dans le même geste.
    ///
    /// Rend la main tout de suite : l'ouverture et ses pannes arrivent par le
    /// flux d'état, comme sur Android.
    let openChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.onyx_player_apple.OnyxApplePlayerApi.open\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        let urlArg = args[1] as! String
        let startPositionMsArg = args[2] as! Int64
        let playArg = args[3] as! Bool
        do {
          try api.open(playerId: playerIdArg, url: urlArg, startPositionMs: startPositionMsArg, play: playArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      openChannel.setMessageHandler(nil)
    }
    let playChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.onyx_player_apple.OnyxApplePlayerApi.play\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      playChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        do {
          try api.play(playerId: playerIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      playChannel.setMessageHandler(nil)
    }
    let pauseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.onyx_player_apple.OnyxApplePlayerApi.pause\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pauseChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        do {
          try api.pause(playerId: playerIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      pauseChannel.setMessageHandler(nil)
    }
    let seekToChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.onyx_player_apple.OnyxApplePlayerApi.seekTo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      seekToChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        let positionMsArg = args[1] as! Int64
        do {
          try api.seekTo(playerId: playerIdArg, positionMs: positionMsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      seekToChannel.setMessageHandler(nil)
    }
    /// Décharge le média sans détruire le lecteur.
    let stopChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.onyx_player_apple.OnyxApplePlayerApi.stop\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        do {
          try api.stop(playerId: playerIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopChannel.setMessageHandler(nil)
    }
    let setVolumeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.onyx_player_apple.OnyxApplePlayerApi.setVolume\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setVolumeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        let volumeArg = args[1] as! Double
        do {
          try api.setVolume(playerId: playerIdArg, volume: volumeArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setVolumeChannel.setMessageHandler(nil)
    }
    let setRateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.onyx_player_apple.OnyxApplePlayerApi.setRate\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setRateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        let rateArg = args[1] as! Double
        do {
          try api.setRate(playerId: playerIdArg, rate: rateArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setRateChannel.setMessageHandler(nil)
    }
    /// Quelle langue audio charger d'emblée, la plus probable en premier. Posé
    /// avant l'ouverture : après, changer de piste reconstruit la session
    /// (une demi-seconde d'image noire).
    let setPreferredAudioLanguagesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.onyx_player_apple.OnyxApplePlayerApi.setPreferredAudioLanguages\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setPreferredAudioLanguagesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        let prioritiesArg = args[1] as! [String]
        do {
          try api.setPreferredAudioLanguages(playerId: playerIdArg, priorities: prioritiesArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setPreferredAudioLanguagesChannel.setMessageHandler(nil)
    }
    let selectAudioTrackChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.onyx_player_apple.OnyxApplePlayerApi.selectAudioTrack\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      selectAudioTrackChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        let trackIdArg = args[1] as! String
        do {
          try api.selectAudioTrack(playerId: playerIdArg, trackId: trackIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      selectAudioTrackChannel.setMessageHandler(nil)
    }
    /// Une piste de sous-titres du média, ou aucune si [trackId] est nul.
    let selectSubtitleTrackChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.onyx_player_apple.OnyxApplePlayerApi.selectSubtitleTrack\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      selectSubtitleTrackChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        let trackIdArg: String? = nilOrValue(args[1])
        do {
          try api.selectSubtitleTrack(playerId: playerIdArg, trackId: trackIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      selectSubtitleTrackChannel.setMessageHandler(nil)
    }
    /// Pose (ou retire, avec null) le WebVTT que le serveur a produit.
    let setExternalSubtitleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.onyx_player_apple.OnyxApplePlayerApi.setExternalSubtitle\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setExternalSubtitleChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        let vttContentArg: String? = nilOrValue(args[1])
        let languageArg: String? = nilOrValue(args[2])
        let titleArg: String? = nilOrValue(args[3])
        do {
          try api.setExternalSubtitle(playerId: playerIdArg, vttContent: vttContentArg, language: languageArg, title: titleArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setExternalSubtitleChannel.setMessageHandler(nil)
    }
    /// L'état à cet instant, pour s'amorcer sans attendre le premier événement.
    let statusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.onyx_player_apple.OnyxApplePlayerApi.status\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      statusChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        do {
          let result = try api.status(playerId: playerIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      statusChannel.setMessageHandler(nil)
    }
    let statsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.onyx_player_apple.OnyxApplePlayerApi.stats\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      statsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        do {
          let result = try api.stats(playerId: playerIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      statsChannel.setMessageHandler(nil)
    }
  }
}

private class PigeonStreamHandler<ReturnType>: NSObject, FlutterStreamHandler {
  private let wrapper: PigeonEventChannelWrapper<ReturnType>
  private var pigeonSink: PigeonEventSink<ReturnType>? = nil

  init(wrapper: PigeonEventChannelWrapper<ReturnType>) {
    self.wrapper = wrapper
  }

  func onListen(withArguments arguments: Any?, eventSink events: @escaping FlutterEventSink)
    -> FlutterError?
  {
    pigeonSink = PigeonEventSink<ReturnType>(events)
    wrapper.onListen(withArguments: arguments, sink: pigeonSink!)
    return nil
  }

  func onCancel(withArguments arguments: Any?) -> FlutterError? {
    pigeonSink = nil
    wrapper.onCancel(withArguments: arguments)
    return nil
  }
}

class PigeonEventChannelWrapper<ReturnType> {
  func onListen(withArguments arguments: Any?, sink: PigeonEventSink<ReturnType>) {}
  func onCancel(withArguments arguments: Any?) {}
}

class PigeonEventSink<ReturnType> {
  private let sink: FlutterEventSink

  init(_ sink: @escaping FlutterEventSink) {
    self.sink = sink
  }

  func success(_ value: ReturnType) {
    sink(value)
  }

  func error(code: String, message: String?, details: Any?) {
    sink(FlutterError(code: code, message: message, details: details))
  }

  func endOfStream() {
    sink(FlutterEndOfEventStream)
  }

}

class StatusChangedStreamHandler: PigeonEventChannelWrapper<OnyxApplePlayerStatus> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: StatusChangedStreamHandler) {
    var channelName = "dev.flutter.pigeon.onyx_player_apple.OnyxApplePlayerEventApi.statusChanged"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<OnyxApplePlayerStatus>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: messagesPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
class SubtitlesChangedStreamHandler: PigeonEventChannelWrapper<OnyxAppleSubtitleFrame> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: SubtitlesChangedStreamHandler) {
    var channelName = "dev.flutter.pigeon.onyx_player_apple.OnyxApplePlayerEventApi.subtitlesChanged"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<OnyxAppleSubtitleFrame>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: messagesPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
class EngineLogStreamHandler: PigeonEventChannelWrapper<[String]> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: EngineLogStreamHandler) {
    var channelName = "dev.flutter.pigeon.onyx_player_apple.OnyxApplePlayerEventApi.engineLog"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<[String]>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: messagesPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
