// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// Où en est le lecteur, dans le vocabulaire d'ExoPlayer.
enum OnyxPlaybackState {
  /// Rien de chargé.
  idle,
  /// Chargé, mais pas assez de données pour avancer.
  buffering,
  /// Prêt à jouer, ou en train de jouer.
  ready,
  /// Arrivé au bout.
  ended,
}

/// Pourquoi une ouverture a échoué.
///
/// Le détail importe : c'est ce qui distingue un fichier qu'il faut transcoder
/// d'un réseau qui a lâché, et donc s'il faut réessayer ou changer de source.
enum OnyxPlayerErrorKind {
  /// Le conteneur ou le codec n'est pas lisible par cet appareil. C'est le cas
  /// qui bascule sur le transcodage.
  unsupported,
  /// La source n'a pas pu être lue : réseau, 404, connexion coupée.
  source,
  /// Tout le reste.
  unknown,
}

/// Comment l'image remplit sa surface.
///
/// Une `SurfaceView` est une couche du système : Flutter ne peut pas la mettre
/// à l'échelle, donc le cadrage se décide côté natif. C'est ce qui fait
/// répondre le pincement et le réglage « taille adaptative » sur Android.
enum OnyxVideoFit {
  /// L'image entière, avec des bandes s'il le faut.
  contain,
  /// Toute la hauteur, quitte à ce que les côtés sortent du cadre.
  ///
  /// C'est ce que « taille d'origine » veut dire sur un téléphone tenu à
  /// l'horizontale : la framing d'origine y arrive sous forme de bandes noires
  /// en haut et en bas dès que le film est plus large que l'écran, ce qui est
  /// le cas de la plupart. Sur un écran qu'on tient, les bandes valent moins
  /// que l'image.
  fillHeight,
  /// La surface entière, en rognant ce qui dépasse.
  cover,
}

/// Une piste que le moteur a énumérée.
class OnyxTrack {
  OnyxTrack({
    required this.id,
    this.title,
    this.language,
  });

  String id;

  String? title;

  String? language;

  List<Object?> _toList() {
    return <Object?>[
      id,
      title,
      language,
    ];
  }

  Object encode() {
    return _toList();  }

  static OnyxTrack decode(Object result) {
    result as List<Object?>;
    return OnyxTrack(
      id: result[0]! as String,
      title: result[1] as String?,
      language: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OnyxTrack || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) && _deepEquals(title, other.title) && _deepEquals(language, other.language);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'OnyxTrack(id: $id, title: $title, language: $language)';
  }
}

/// Les tampons, dans les unités d'ExoPlayer.
///
/// `PlaybackProfile` les exprime en octets et en secondes, parce que c'est le
/// vocabulaire de mpv ; `DefaultLoadControl` ne connaît que des millisecondes.
/// La traduction se fait côté Dart, où le profil est déjà résolu.
class OnyxLoadTuning {
  OnyxLoadTuning({
    required this.minBufferMs,
    required this.maxBufferMs,
    required this.bufferForPlaybackMs,
    required this.backBufferMs,
  });

  int minBufferMs;

  int maxBufferMs;

  /// Ce qu'il faut avoir en mémoire avant que l'image ne parte. Court : c'est
  /// du temps ajouté devant la première image, à chaque ouverture.
  int bufferForPlaybackMs;

  /// Ce qu'on garde derrière la tête de lecture, pour que le retour de 10 s ne
  /// reparte pas sur le réseau.
  int backBufferMs;

  List<Object?> _toList() {
    return <Object?>[
      minBufferMs,
      maxBufferMs,
      bufferForPlaybackMs,
      backBufferMs,
    ];
  }

  Object encode() {
    return _toList();  }

  static OnyxLoadTuning decode(Object result) {
    result as List<Object?>;
    return OnyxLoadTuning(
      minBufferMs: result[0]! as int,
      maxBufferMs: result[1]! as int,
      bufferForPlaybackMs: result[2]! as int,
      backBufferMs: result[3]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OnyxLoadTuning || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(minBufferMs, other.minBufferMs) && _deepEquals(maxBufferMs, other.maxBufferMs) && _deepEquals(bufferForPlaybackMs, other.bufferForPlaybackMs) && _deepEquals(backBufferMs, other.backBufferMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'OnyxLoadTuning(minBufferMs: $minBufferMs, maxBufferMs: $maxBufferMs, bufferForPlaybackMs: $bufferForPlaybackMs, backBufferMs: $backBufferMs)';
  }
}

class OnyxVideoSize {
  OnyxVideoSize({
    required this.width,
    required this.height,
  });

  int width;

  int height;

  List<Object?> _toList() {
    return <Object?>[
      width,
      height,
    ];
  }

  Object encode() {
    return _toList();  }

  static OnyxVideoSize decode(Object result) {
    result as List<Object?>;
    return OnyxVideoSize(
      width: result[0]! as int,
      height: result[1]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OnyxVideoSize || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(width, other.width) && _deepEquals(height, other.height);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'OnyxVideoSize(width: $width, height: $height)';
  }
}

/// Un instantané complet de l'état du lecteur.
///
/// Un seul objet plutôt qu'un événement par propriété : l'appelant n'a qu'un
/// état à réconcilier, et deux champs ne peuvent pas se contredire en chemin.
class OnyxPlayerStatus {
  OnyxPlayerStatus({
    required this.playerId,
    required this.state,
    required this.isPlaying,
    required this.positionMs,
    required this.durationMs,
    required this.bufferedPositionMs,
    this.videoSize,
    required this.audioTracks,
    required this.subtitleTracks,
    this.selectedAudioTrackId,
    this.selectedSubtitleTrackId,
    required this.subtitleCues,
    this.errorKind,
    this.errorMessage,
  });

  int playerId;

  OnyxPlaybackState state;

  /// Le lecteur avance réellement — distinct de « on lui a demandé de lire ».
  bool isPlaying;

  int positionMs;

  /// 0 tant qu'ExoPlayer ne connaît pas la durée (flux en cours de sondage).
  int durationMs;

  int bufferedPositionMs;

  /// Null tant que le décodeur n'a pas annoncé les dimensions.
  OnyxVideoSize? videoSize;

  /// Les pistes que le moteur a trouvées dans ce média.
  List<OnyxTrack> audioTracks;

  List<OnyxTrack> subtitleTracks;

  String? selectedAudioTrackId;

  String? selectedSubtitleTrackId;

  /// Les lignes de sous-titre à afficher maintenant. Rendues côté Flutter, pour
  /// que l'habillage soit le même que sur les autres plateformes.
  List<String> subtitleCues;

  OnyxPlayerErrorKind? errorKind;

  String? errorMessage;

  List<Object?> _toList() {
    return <Object?>[
      playerId,
      state,
      isPlaying,
      positionMs,
      durationMs,
      bufferedPositionMs,
      videoSize,
      audioTracks,
      subtitleTracks,
      selectedAudioTrackId,
      selectedSubtitleTrackId,
      subtitleCues,
      errorKind,
      errorMessage,
    ];
  }

  Object encode() {
    return _toList();  }

  static OnyxPlayerStatus decode(Object result) {
    result as List<Object?>;
    return OnyxPlayerStatus(
      playerId: result[0]! as int,
      state: result[1]! as OnyxPlaybackState,
      isPlaying: result[2]! as bool,
      positionMs: result[3]! as int,
      durationMs: result[4]! as int,
      bufferedPositionMs: result[5]! as int,
      videoSize: result[6] as OnyxVideoSize?,
      audioTracks: (result[7]! as List<Object?>).cast<OnyxTrack>(),
      subtitleTracks: (result[8]! as List<Object?>).cast<OnyxTrack>(),
      selectedAudioTrackId: result[9] as String?,
      selectedSubtitleTrackId: result[10] as String?,
      subtitleCues: (result[11]! as List<Object?>).cast<String>(),
      errorKind: result[12] as OnyxPlayerErrorKind?,
      errorMessage: result[13] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OnyxPlayerStatus || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(playerId, other.playerId) && _deepEquals(state, other.state) && _deepEquals(isPlaying, other.isPlaying) && _deepEquals(positionMs, other.positionMs) && _deepEquals(durationMs, other.durationMs) && _deepEquals(bufferedPositionMs, other.bufferedPositionMs) && _deepEquals(videoSize, other.videoSize) && _deepEquals(audioTracks, other.audioTracks) && _deepEquals(subtitleTracks, other.subtitleTracks) && _deepEquals(selectedAudioTrackId, other.selectedAudioTrackId) && _deepEquals(selectedSubtitleTrackId, other.selectedSubtitleTrackId) && _deepEquals(subtitleCues, other.subtitleCues) && _deepEquals(errorKind, other.errorKind) && _deepEquals(errorMessage, other.errorMessage);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'OnyxPlayerStatus(playerId: $playerId, state: $state, isPlaying: $isPlaying, positionMs: $positionMs, durationMs: $durationMs, bufferedPositionMs: $bufferedPositionMs, videoSize: $videoSize, audioTracks: $audioTracks, subtitleTracks: $subtitleTracks, selectedAudioTrackId: $selectedAudioTrackId, selectedSubtitleTrackId: $selectedSubtitleTrackId, subtitleCues: $subtitleCues, errorKind: $errorKind, errorMessage: $errorMessage)';
  }
}

/// Ce qu'il faut pour répondre à « est-ce que c'est fluide ? » par un chiffre.
///
/// C'est le critère de recette du premier jalon : comparable au
/// `frame-drop-count` que le lecteur mpv journalise déjà en sortie.
class OnyxPlaybackStats {
  OnyxPlaybackStats({
    required this.droppedFrames,
    required this.renderedFrames,
  });

  int droppedFrames;

  int renderedFrames;

  List<Object?> _toList() {
    return <Object?>[
      droppedFrames,
      renderedFrames,
    ];
  }

  Object encode() {
    return _toList();  }

  static OnyxPlaybackStats decode(Object result) {
    result as List<Object?>;
    return OnyxPlaybackStats(
      droppedFrames: result[0]! as int,
      renderedFrames: result[1]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OnyxPlaybackStats || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(droppedFrames, other.droppedFrames) && _deepEquals(renderedFrames, other.renderedFrames);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'OnyxPlaybackStats(droppedFrames: $droppedFrames, renderedFrames: $renderedFrames)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is OnyxPlaybackState) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is OnyxPlayerErrorKind) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is OnyxVideoFit) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is OnyxTrack) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is OnyxLoadTuning) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is OnyxVideoSize) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is OnyxPlayerStatus) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is OnyxPlaybackStats) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : OnyxPlaybackState.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : OnyxPlayerErrorKind.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : OnyxVideoFit.values[value];
      case 132:
        return OnyxTrack.decode(readValue(buffer)!);
      case 133:
        return OnyxLoadTuning.decode(readValue(buffer)!);
      case 134:
        return OnyxVideoSize.decode(readValue(buffer)!);
      case 135:
        return OnyxPlayerStatus.decode(readValue(buffer)!);
      case 136:
        return OnyxPlaybackStats.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

const StandardMethodCodec pigeonMethodCodec = StandardMethodCodec(_PigeonCodec());

class OnyxPlayerApi {
  /// Constructor for [OnyxPlayerApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  OnyxPlayerApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Crée un lecteur et rend son identifiant. La vue de rendu s'y rattache par
  /// cet identifiant, ce qui permet de créer le lecteur avant que la vue
  /// n'existe — et de survivre à sa reconstruction.
  Future<int> create() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onyx_player_android.OnyxPlayerApi.create$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }

  /// Détruit le lecteur. Sans appel, ExoPlayer garde son décodeur et sa
  /// connexion réseau ouverts.
  Future<void> release(int playerId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onyx_player_android.OnyxPlayerApi.release$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[playerId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Charge [url] et se positionne à [startPositionMs] dans le même geste.
  /// Ouvrir puis chercher ferait payer deux fois la mise en mémoire tampon.
  ///
  /// [play] démarre la lecture dès que le média est prêt, sans second aller-
  /// retour : c'est ce que fait le passage à l'épisode suivant.
  Future<void> open(int playerId, String url, int startPositionMs, bool play) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onyx_player_android.OnyxPlayerApi.open$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[playerId, url, startPositionMs, play]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> play(int playerId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onyx_player_android.OnyxPlayerApi.play$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[playerId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> pause(int playerId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onyx_player_android.OnyxPlayerApi.pause$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[playerId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> seekTo(int playerId, int positionMs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onyx_player_android.OnyxPlayerApi.seekTo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[playerId, positionMs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Décharge le média sans détruire le lecteur.
  ///
  /// C'est ici que le décodeur matériel est rendu — l'opération la plus chère
  /// du démontage. L'appeler tôt fait qu'elle se paie pendant qu'autre chose
  /// se passe à l'écran, plutôt qu'après.
  Future<void> stop(int playerId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onyx_player_android.OnyxPlayerApi.stop$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[playerId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> setVolume(int playerId, double volume) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onyx_player_android.OnyxPlayerApi.setVolume$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[playerId, volume]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> setRate(int playerId, double rate) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onyx_player_android.OnyxPlayerApi.setRate$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[playerId, rate]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Quelle langue audio charger d'emblée, la plus probable en premier. Posé
  /// avant l'ouverture — après, changer de piste recharge le tampon.
  Future<void> setPreferredAudioLanguages(int playerId, List<String> priorities) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onyx_player_android.OnyxPlayerApi.setPreferredAudioLanguages$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[playerId, priorities]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> selectAudioTrack(int playerId, String trackId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onyx_player_android.OnyxPlayerApi.selectAudioTrack$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[playerId, trackId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Sélectionne une piste de sous-titres interne, ou aucune si [trackId] est
  /// nul.
  Future<void> selectSubtitleTrack(int playerId, String? trackId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onyx_player_android.OnyxPlayerApi.selectSubtitleTrack$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[playerId, trackId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Charge un WebVTT que le serveur a produit, en le posant à côté du média.
  ///
  /// Le contenu est passé plutôt qu'une URL : c'est le contrôleur qui l'a
  /// téléchargé, et le serveur a déjà recalé les temps sur l'offset du flux.
  Future<void> setExternalSubtitle(int playerId, String? vttContent, String? language, String? title) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onyx_player_android.OnyxPlayerApi.setExternalSubtitle$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[playerId, vttContent, language, title]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Cherche à l'image près, ou au point-clé le plus proche pendant qu'on fait
  /// glisser la tête de lecture.
  Future<void> setExactSeek(int playerId, bool exact) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onyx_player_android.OnyxPlayerApi.setExactSeek$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[playerId, exact]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> setVideoFit(int playerId, OnyxVideoFit fit) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onyx_player_android.OnyxPlayerApi.setVideoFit$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[playerId, fit]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Impose la durée totale : en transcodage, le moteur ne voit que les
  /// segments déjà produits.
  Future<void> overrideDuration(int playerId, int totalMs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onyx_player_android.OnyxPlayerApi.overrideDuration$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[playerId, totalMs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> applyTuning(int playerId, OnyxLoadTuning tuning) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onyx_player_android.OnyxPlayerApi.applyTuning$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[playerId, tuning]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Les types MIME audio que la puce sait décoder.
  ///
  /// mpv décodait tout en logiciel ; ExoPlayer dépend de MediaCodec. Demandé
  /// une fois, pour que le contrôleur puisse trancher lecture directe ou
  /// transcodage **avant** d'ouvrir, plutôt que d'échouer devant l'utilisateur.
  Future<List<String>> decodableAudioMimeTypes() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onyx_player_android.OnyxPlayerApi.decodableAudioMimeTypes$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<String>();
  }

  /// L'état à cet instant. Les changements arrivent par le flux d'événements ;
  /// ceci sert à s'amorcer sans attendre le premier.
  Future<OnyxPlayerStatus> status(int playerId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onyx_player_android.OnyxPlayerApi.status$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[playerId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as OnyxPlayerStatus;
  }

  /// Les compteurs d'images du rendu vidéo.
  Future<OnyxPlaybackStats> stats(int playerId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.onyx_player_android.OnyxPlayerApi.stats$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[playerId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as OnyxPlaybackStats;
  }
}

/// Un flux unique pour tous les lecteurs — [OnyxPlayerStatus.playerId] dit
/// lequel. Un canal par lecteur coûterait une négociation à chaque ouverture
/// pour distinguer des instances qui n'existent jamais à plus de deux.
///
/// Returns a broadcast [Stream] of events from the `statusChanged` event channel.
///
/// Each call to this method creates a new [EventChannel], so it should
/// not be called multiple times for the same `instanceName`. To deliver
/// events to multiple listeners, call this method once and listen to the
/// returned broadcast stream multiple times instead.
Stream<OnyxPlayerStatus> statusChanged( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel statusChangedChannel =
      EventChannel('dev.flutter.pigeon.onyx_player_android.OnyxPlayerEventApi.statusChanged$instanceName', pigeonMethodCodec);
  return statusChangedChannel.receiveBroadcastStream().map((dynamic event) {
    return event as OnyxPlayerStatus;
  });
}
    
